function uiObj = CreateBackground(BCI)
screenSize = get(0,'screensize');
w = 1142; h = 729;
bgPos = [(screenSize(3)-w)/2 (screenSize(4)-h)/2 w h];

uiObj = uifigure('NumberTitle','off', ...
    'units','pixels', ...
    'position', bgPos, ...
    'menubar','none', ...
    'name','', ...
    'resize','off');

uiObj.Icon = 'img/icon_48.png';
% -----------------------------------------------------------------------
% Move the background axes to the bottom
bgimg = uiimage(uiObj);
bgimg.Position = [0 0 w h];
bgimg.ImageSource = imread('img\background.png');
% -----------------------------------------------------------------------
txt = {'Home Appliance Control'; 'BCI System Using ERP'};
uilabel(uiObj, 'Position', [15 400 w 400],...
    'Text',txt,...
    'FontName', 'Arial Black',...
    'FontSize',40,...
    'FontWeight', 'bold',...
    'FontColor', 'w',...
    'BackgroundColor', 'none');
% -----------------------------------------------------------------------
% create set path button
uibutton(uiObj,...
    'Text', 'Set path',...
    'position',[20 130 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn', @(src, event)PushedButtons(src, event, BCI,'set'));
% -----------------------------------------------------------------------
% create setting options button
uibutton(uiObj,...
    'Text', 'Setting',...
    'position',[170 130 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn',  @(src, event)PushedButtons(src, event, BCI,'setting'));
% -----------------------------------------------------------------------
% create selecting mode button
uidropdown(uiObj,...
    'Items', {'','Virtual' 'Real'},...
    'Placeholder','           Mode',...
    'position',[320 130 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ValueChangedFcn', @(src, event)PushedButtons(src, event, BCI,'mode'));
% -----------------------------------------------------------------------
% create connect button
uibutton(uiObj,...
    'Text', 'Connect',...
    'position',[20 70 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn', @(src, event)PushedButtons(src, event, BCI,'con'));
% -----------------------------------------------------------------------
% create start button
uibutton(uiObj,...
    'Text', 'Start',...
    'position',[170 70 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn', @(src, event)PushedButtons(src, event, BCI,'start'));
% -----------------------------------------------------------------------
% create save button
uibutton(uiObj,...
    'Text', 'Save',...
    'position',[320 70 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn', @(src, event)PushedButtons(src, event, BCI,'save'));
% -----------------------------------------------------------------------
% create help button
uibutton(uiObj,...
    'Text', 'Help',...
    'position',[1000 20 120 40],...
    'FontName','Calibri Light',...
    'FontSize', 15,...
    'FontAngle','italic',...
    'FontColor','w',...
    'BackgroundColor',[.15 .15 .18],...
    'ButtonPushedFcn', @(src, event)PushedButtons(src, event, BCI,'help'));


% -----------------------------------------------------------------------
% Alarm for application
subpos = [(screenSize(3)-w)/2 (screenSize(4)-h)/2 1202/2 floor(767/2)];
subui = uifigure('NumberTitle','off', ...
    'units','pixels', ...
    'position', subpos, ...
    'menubar','none', ...
    'name','', ...
    'resize','off');

subimg = uiimage(subui);
subimg.Position = [0 0 subpos(3) subpos(4)];
subimg.ImageSource = imread('img\network_setting.jpg');

txt = {'You need to set option'; 'before using.'; 'Follow steps!'};
uilabel(subui, 'Position', [15 10 subpos(3) 400],...
    'Text',txt,...
    'FontName', 'Arial Black',...
    'FontSize',32,...
    'FontWeight', 'bold',...
    'FontColor', 'k',...
    'BackgroundColor', 'none');